### ISSUE TITLE
Unable to execute IE tests!!

### ISSUE THREAD

**Issue by acbharat** [krupani/testnow#2]
Getting syntax error, when I tried to execute tests in IE..

**Comment by krupani** [comment]
Thanks for bringing into notice, this will be fixed in the next release of v0.0.9

Estimated release date is by 1st Dec.

**Comment by krupani** [comment]
Issue resolved in version 0.0.9, please upgrade your gem to latest version...

[Note: If you are using a 64bit Windows machine, the IE Driver to use is 32 bit only, do not use IEDriver 64 bit. ]

Thanks!!
